-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here

-- Reset cursor shape on exit (tmux)
-- vim.api.nvim_exec(
--   [[
--   augroup ChangeCursorShape
--     autocmd!
--     autocmd VimLeave * call system("echo -ne '\e[6 q'")
--   augroup END
-- ]],
--   true
-- )
